"""Regression for a missing general primitive found solving a real target:
listing and extracting a PE's embedded resources. A real solve attempt on
benchmarks/real_corpora/cm1_unpack_reactor/extracted/CrackBeePck.exe (a
.NET Reactor native stub) needed to read an RT_RCDATA resource named "__"
holding the encrypted managed assembly payload, and had to call `pefile`
inline because no tool existed for it -- a repo-wide grep for resource
enumeration found only android_resource_analyzer, which is APK-only.

WHY THIS IS GENERAL, not target-specific: hiding a payload in a resource is
one of the most common packer/dropper/loader patterns there is (droppers,
self-extracting installers, embedded drivers, icon/overlay stuffing all use
the same PE resource directory shape). tools_binary.pe_resources is built
entirely on pefile's own already-vendored DIRECTORY_ENTRY_RESOURCE walker
-- no new resource parser -- and lives in tools_binary.py alongside this
module's other PE-level facts (pe_sections/pe_imports/pe_exports/
authenticode_signature).

Ground truth for the hash check below is a real, independent `pefile`
extraction performed outside this tool during the same solve session (not
generated by the code under test), so it is a real correctness check.
"""
from __future__ import annotations

import hashlib
import json
import unittest
from pathlib import Path

import liebert_re.workspace as tools_workspace
from liebert_re.tools.binary import pe_resources

CRACKBEE = Path(tools_workspace.WORKSPACE) / "benchmarks" / "real_corpora" / "cm1_unpack_reactor" / "extracted" / "CrackBeePck.exe"
RASM = Path(tools_workspace.WORKSPACE) / "benchmarks" / "real_corpora" / "cm1_ring0_keygenme" / "extracted" / "rAsM_kGm_x" / "rAsM_kGm.exe"
NO_RESOURCES = Path(tools_workspace.WORKSPACE) / "benchmarks" / "real_corpora" / "cm1_crackme_speedrun" / "extracted" / "CrackmeSpeedrun_x" / "crackme.exe"

EXPECTED_SHA256 = "c6fb32c8c2e2bfd73fca3279c81aff7d76f4242ae603b5a2122843ee1cfd0e6b"


@unittest.skipUnless(CRACKBEE.exists(), "real corpus target CrackBeePck.exe missing")
class PeResourcesListTests(unittest.TestCase):
    def test_list_finds_the_reactor_payload_and_the_second_rcdata(self):
        result = json.loads(pe_resources(str(CRACKBEE), operation="list"))
        self.assertTrue(result.get("ok"), result)
        self.assertTrue(result["has_resource_directory"])
        rcdata = [r for r in result["resources"] if r["type_well_known"] == "RT_RCDATA"]
        self.assertEqual(len(rcdata), 2)
        payload = next(r for r in rcdata if r["name"] == "__")
        self.assertEqual(payload["size"], 49674)
        self.assertGreater(payload["entropy"], 7.9)  # known encrypted-payload signature
        marker = next(r for r in rcdata if r["name"] == "~")
        self.assertEqual(marker["size"], 32)

    def test_list_is_paginated(self):
        result = json.loads(pe_resources(str(CRACKBEE), operation="list", max_results=1))
        self.assertTrue(result.get("ok"), result)
        self.assertEqual(result["returned"], 1)
        self.assertTrue(result["has_more"])
        self.assertGreater(result["total"], 1)


@unittest.skipUnless(CRACKBEE.exists(), "real corpus target CrackBeePck.exe missing")
class PeResourcesExtractHashTests(unittest.TestCase):
    def test_extract_matches_known_ground_truth_sha256(self):
        result = json.loads(pe_resources(str(CRACKBEE), operation="extract", resource_type="RT_RCDATA", resource_name="__"))
        self.assertTrue(result.get("ok"), result)
        self.assertEqual(result["size"], 49674)
        self.assertEqual(result["sha256"], EXPECTED_SHA256)

        evidence_path = Path(result["evidence_file"])
        self.assertTrue(evidence_path.exists())
        payload = evidence_path.read_bytes()
        self.assertEqual(len(payload), 49674)
        self.assertEqual(hashlib.sha256(payload).hexdigest(), EXPECTED_SHA256)
        # Bytes never returned inline in full -- only a bounded preview.
        self.assertLess(result["preview_returned_bytes"], 49674)
        self.assertTrue(result["preview_truncated"])
        self.assertEqual(bytes.fromhex(result["preview_hex"]), payload[: result["preview_returned_bytes"]])

    def test_extract_by_numeric_type_id_matches_rt_constant(self):
        result = json.loads(pe_resources(str(CRACKBEE), operation="extract", resource_type="10", resource_name="__"))
        self.assertTrue(result.get("ok"), result)
        self.assertEqual(result["sha256"], EXPECTED_SHA256)


@unittest.skipUnless(RASM.exists(), "real corpus target rAsM_kGm.exe missing")
class PeResourcesAmbiguousSelectorTests(unittest.TestCase):
    def test_selector_matching_multiple_resources_returns_all_not_one(self):
        result = json.loads(pe_resources(str(RASM), operation="extract", resource_type="RT_ICON"))
        self.assertFalse(result.get("ok"))
        self.assertEqual(result.get("error"), "AMBIGUOUS_SELECTOR")
        self.assertEqual(len(result["matches"]), 4)
        self.assertEqual({m["name_id"] for m in result["matches"]}, {1, 2, 3, 4})

    def test_adding_name_disambiguates(self):
        result = json.loads(pe_resources(str(RASM), operation="extract", resource_type="RT_ICON", resource_name="2"))
        self.assertTrue(result.get("ok"), result)
        self.assertEqual(result["size"], 9640)

    def test_list_reports_ordinary_icon_and_version_style_resources(self):
        result = json.loads(pe_resources(str(RASM), operation="list"))
        self.assertTrue(result.get("ok"), result)
        types = {r["type_well_known"] for r in result["resources"]}
        self.assertIn("RT_ICON", types)
        self.assertIn("RT_MANIFEST", types)


@unittest.skipUnless(NO_RESOURCES.exists(), "real corpus target with no resource directory missing")
class PeResourcesNoResourceDirectoryTests(unittest.TestCase):
    def test_list_reports_cleanly_not_an_error(self):
        result = json.loads(pe_resources(str(NO_RESOURCES), operation="list"))
        self.assertTrue(result.get("ok"), result)
        self.assertFalse(result["has_resource_directory"])
        self.assertEqual(result["resources"], [])
        self.assertEqual(result["total"], 0)

    def test_extract_refuses_with_a_named_reason(self):
        result = json.loads(pe_resources(str(NO_RESOURCES), operation="extract", resource_type="RT_ICON"))
        self.assertFalse(result.get("ok"))
        self.assertEqual(result.get("error"), "NO_RESOURCE_DIRECTORY")


@unittest.skipUnless(RASM.exists(), "real corpus target rAsM_kGm.exe missing")
class PeResourcesMalformedTests(unittest.TestCase):
    """A resource that pefile's own out-of-bounds clamp silently truncates
    (declares a Size larger than the bytes actually available) must be
    reported as a structured error, never presented as a complete
    resource. Built from a real corpus binary truncated to 30% of its
    real length -- not a synthetic byte pattern -- so the corruption shape
    (OOB resource data, not a bad header) matches what a real truncated
    download/dump looks like."""

    def setUp(self):
        real_bytes = RASM.read_bytes()
        self.truncated_dir = tools_workspace.WORKSPACE_ROOT / "dataset" / "runtime" / "pe_resources_test_scratch"
        self.truncated_dir.mkdir(parents=True, exist_ok=True)
        self.truncated_path = self.truncated_dir / "truncated_rAsM_kGm.exe"
        self.truncated_path.write_bytes(real_bytes[: int(len(real_bytes) * 0.3)])
        self.addCleanup(self._cleanup)

    def _cleanup(self):
        import shutil
        shutil.rmtree(self.truncated_dir, ignore_errors=True)

    def test_truncated_resource_data_is_a_structured_error_not_a_partial_tree(self):
        result = json.loads(pe_resources(str(self.truncated_path), operation="list"))
        self.assertFalse(result.get("ok"))
        self.assertEqual(result.get("error"), "RESOURCE_DATA_MALFORMED")
        self.assertIn("truncated or corrupt", result.get("detail", ""))

    def test_truncated_resource_data_also_refuses_extract(self):
        result = json.loads(pe_resources(str(self.truncated_path), operation="extract", resource_type="RT_MANIFEST"))
        self.assertFalse(result.get("ok"))
        self.assertIn(result.get("error"), {"RESOURCE_DATA_MALFORMED", "RESOURCE_NOT_FOUND"})


if __name__ == "__main__":
    unittest.main()


# --- heavy marker (test-suite split: fast baseline vs external-tool integration) ---
# This test invokes (directly or via an imported tools_*/tools_emulation*/kernel_corpus/
# environment_contamination_check/isolated_artifact/phase81_live_control/runpod_acceptance
# module) a real external analysis tool or spawns a bounded subprocess -- these can be
# slow or hang, so they are excluded from the default run and must be run explicitly
# with `pytest -m heavy`. See pytest.ini in this repo for the tools actually involved.
import pytest as _pytest_heavy_marker
pytestmark = _pytest_heavy_marker.mark.heavy
